'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def test_sumaTermFibo():
    assert sumaTermFibo(2) == 2
    assert sumaTermFibo(10) == 10
    assert sumaTermFibo(30) == 10
    assert sumaTermFibo(90) == 44

def isEven(numar):
    if numar%2==0:
        return 1
    return 0

def sumaTermFibo(value):
    if value <1:
        return 0
    elif value <2:
        return 1
    else:
        suma = 0
        a = 1
        b = 2
        while b<=value:
            if isEven(b)==1:
                suma = suma+b
            aux = a+b
            a = b
            b = aux
    return suma

def main():
    print("Dati valoarea de sfarsit: ", end = "")
    nrTerm = int(input())
    suma = sumaTermFibo(nrTerm ) #calculeaza suma termenilor sirului fibonaci pana
                                 #la o anumita valoare
    print("Suma termenilor este: ", suma)

main()
test_sumaTermFibo()
